"""Generates the learnable_ppr.ipynb notebook."""
import json

nb = {
    "cells": [],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.13.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

def md(src):
    nb["cells"].append({"cell_type": "markdown", "metadata": {}, "source": [src]})

def code(src):
    nb["cells"].append({"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [src]})


md("# Learnable PPR Subgraph Selection \n\n**Phase 1**: Architecture search learns per-edge `(teleport_u, teleport_v)` via bi-level optimization on the full graph.\\\n**Phase 2**: Fine-tune a GNN on extracted subgraphs using the learned configurations.\n\nInspired by [PS2 (WSDM'23)](https://github.com/qiaoyu-tan/PS2) which learns per-edge `(k_u, k_v)` for k-hop.")

code(
"# === CONFIGURABLE SEARCH SPACE ===\n"
"# Edit these values to change the PPR search space.\n"
"# Number of configurations = len(TELEPORT_VALUES)^2\n"
"\n"
"TELEPORT_VALUES = [0.50, 0.85, 0.95]   # PPR teleport probabilities\n"
"ALPHA = 0.5                              # Fixed alpha for combining PPR_u + PPR_v\n"
"TOP_K = 100                              # Subgraph size for Phase 2\n"
"\n"
"DATASETS = ['FB15K237']                  # FB15K237, WN18RR, NELL-995\n"
"ENCODERS = ['SAGE']                      # GCN, SAGE, GAT\n"
"\n"
"# Hyperparameters\n"
"FEATURE_DIM = 128\n"
"HIDDEN_CHANNELS = 256\n"
"NUM_LAYERS = 3\n"
"DROPOUT = 0.3\n"
"\n"
"# Phase 1: Architecture Search\n"
"SEARCH_EPOCHS = 50\n"
"SEARCH_BATCH_SIZE = 1024\n"
"SEARCH_LR = 0.01\n"
"SEARCH_PATIENCE = 50\n"
"TEMPERATURE = 0.07\n"
"\n"
"# Phase 2: Fine-tuning\n"
"FINETUNE_EPOCHS = 200\n"
"FINETUNE_BATCH_SIZE = 8192\n"
"FINETUNE_LR = 0.005\n"
"FINETUNE_PATIENCE = 20\n"
"MAX_SUBGRAPHS_PER_FORWARD = 256\n"
"EDGES_PER_EPOCH = 100000           # subsample training edges per epoch (None = use all)\n"
"\n"
"import torch\n"
"DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
"print(f'Device: {DEVICE}')\n"
"print(f'Search space: {len(TELEPORT_VALUES)}x{len(TELEPORT_VALUES)} = {len(TELEPORT_VALUES)**2} configs')"
)

code(
"import numpy as np\n"
"import matplotlib.pyplot as plt\n"
"import seaborn as sns\n"
"from sklearn.manifold import TSNE\n"
"import json, os, time, copy\n"
"import pandas as pd\n"
"\n"
"sns.set_theme(style='whitegrid', palette='muted')\n"
"\n"
"from subgrapher.benchmark.data_prep import prepare_link_prediction_data\n"
"from subgrapher.utils.models import GCN, SAGE, GAT, LinkPredictor\n"
"from subgrapher.benchmark_learnable_ppr.multi_scale_ppr import MultiScalePPR\n"
"from subgrapher.benchmark_learnable_ppr.autolink_ppr import AutoLinkPPR\n"
"from subgrapher.benchmark_learnable_ppr.search_net import PPRSearchNet\n"
"from subgrapher.benchmark_learnable_ppr.searcher import ArchitectureSearcher\n"
"from subgrapher.benchmark_learnable_ppr.finetuner import finetune_on_subgraphs, LearnablePPRExtractor, SubgraphCache, build_or_load_cache\n"
"from subgrapher.benchmark_learnable_ppr.evaluator import evaluate_learnable_ppr, print_evaluation_results\n"
"from subgrapher.benchmark_learnable_ppr.artifacts import save_learnable_ppr_experiment"
)

md("## 1. Data Loading and Multi-Scale PPR")

code(
"DATASET_PATHS = {\n"
"    'FB15K237': 'data/FB15K237/train.txt',\n"
"    'WN18RR': 'data/WN18RR/train.txt',\n"
"    'NELL-995': 'data/NELL-995/train.txt',\n"
"}\n"
"\n"
"all_results = {}\n"
"\n"
"for dataset_name in DATASETS:\n"
"    print(f'\\n{\"=\" * 60}')\n"
"    print(f'Dataset: {dataset_name}')\n"
"    print(f'{\"=\" * 60}')\n"
"\n"
"    dataset_dict = prepare_link_prediction_data(\n"
"        DATASET_PATHS[dataset_name],\n"
"        feature_method='random', feature_dim=FEATURE_DIM)\n"
"\n"
"    data = dataset_dict['data']\n"
"    split_edge = dataset_dict['split_edge']\n"
"\n"
"    print(f'Nodes: {data.num_nodes}, Edges: {data.edge_index.size(1)}')\n"
"    print(f'Train: {split_edge[\"train\"][\"source_node\"].size(0)}, '\n"
"          f'Val: {split_edge[\"valid\"][\"source_node\"].size(0)}, '\n"
"          f'Test: {split_edge[\"test\"][\"source_node\"].size(0)}')\n"
"\n"
"    print(f'\\nLoading multi-scale PPR (teleport={TELEPORT_VALUES})...')\n"
"    multi_scale_ppr = MultiScalePPR(\n"
"        dataset_name, data, teleport_values=TELEPORT_VALUES)\n"
"    print(multi_scale_ppr)\n"
"\n"
"    all_results[dataset_name] = {\n"
"        'data': data, 'split_edge': split_edge,\n"
"        'multi_scale_ppr': multi_scale_ppr, 'experiments': {},\n"
"    }"
)

md("## 2. Phase 1: Architecture Search")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    data = r['data']; split_edge = r['split_edge']; msp = r['multi_scale_ppr']\n"
"    num_configs = msp.num_configs\n"
"\n"
"    for enc_type in ENCODERS:\n"
"        print(f'\\nPhase 1: {dataset_name} / {enc_type}')\n"
"\n"
"        model = AutoLinkPPR(\n"
"            in_channels=FEATURE_DIM, hidden_channels=HIDDEN_CHANNELS,\n"
"            num_layers=NUM_LAYERS, dropout=DROPOUT,\n"
"            gnn_type=enc_type, num_configs=num_configs)\n"
"\n"
"        arch_net = PPRSearchNet(\n"
"            in_channels=HIDDEN_CHANNELS, hidden_channels=256,\n"
"            num_layers=3, temperature=TEMPERATURE)\n"
"\n"
"        searcher = ArchitectureSearcher(\n"
"            model, arch_net, msp, data, split_edge,\n"
"            device=DEVICE, lr=SEARCH_LR, lr_arch=SEARCH_LR)\n"
"\n"
"        search_history = searcher.search(\n"
"            epochs=SEARCH_EPOCHS, batch_size=SEARCH_BATCH_SIZE,\n"
"            patience=SEARCH_PATIENCE, verbose=True)\n"
"\n"
"        train_configs, train_counts = searcher.get_edge_configs('train')\n"
"        val_configs, val_counts = searcher.get_edge_configs('valid')\n"
"        test_configs, test_counts = searcher.get_edge_configs('test')\n"
"\n"
"        r['experiments'][enc_type] = {\n"
"            'search_history': search_history,\n"
"            'model': model, 'arch_net': arch_net,\n"
"            'train_configs': train_configs, 'val_configs': val_configs,\n"
"            'test_configs': test_configs,\n"
"            'train_counts': train_counts, 'val_counts': val_counts,\n"
"            'test_counts': test_counts,\n"
"        }\n"
"\n"
"        print(f'Search done in {search_history[\"total_time\"]:.1f}s')\n"
"        print(f'Train config counts: {train_counts.tolist()}')"
)

md("## 3. Config Distribution Heatmap")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    msp = r['multi_scale_ppr']; S = msp.num_scales\n"
"\n"
"    for enc_type in ENCODERS:\n"
"        exp = r['experiments'][enc_type]\n"
"\n"
"        fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n"
"        for ax, (split, counts) in zip(axes, [\n"
"            ('Train', exp['train_counts']),\n"
"            ('Valid', exp['val_counts']),\n"
"            ('Test', exp['test_counts']),\n"
"        ]):\n"
"            matrix = counts.numpy().reshape(S, S).astype(float)\n"
"            total = matrix.sum()\n"
"            pct = 100 * matrix / max(total, 1)\n"
"            annot = np.array([[f'{int(matrix[i,j])}\\n({pct[i,j]:.1f}%)'\n"
"                               for j in range(S)] for i in range(S)])\n"
"            sns.heatmap(pct, annot=annot, fmt='',\n"
"                        xticklabels=[f'{t}' for t in msp.teleport_values],\n"
"                        yticklabels=[f'{t}' for t in msp.teleport_values],\n"
"                        cmap='YlOrRd', vmin=0, ax=ax)\n"
"            ax.set_xlabel('teleport_v'); ax.set_ylabel('teleport_u')\n"
"            ax.set_title(f'{split} ({int(total)} edges)')\n"
"\n"
"        fig.suptitle(f'{dataset_name} / {enc_type} -- Learned Config Distribution',\n"
"                     fontsize=14, fontweight='bold')\n"
"        plt.tight_layout(); plt.show()"
)

md("## 4. Architecture Search Training Curves")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    for enc_type in ENCODERS:\n"
"        hist = r['experiments'][enc_type]['search_history']\n"
"        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n"
"\n"
"        epochs_list = range(1, len(hist['search_loss']) + 1)\n"
"        sns.lineplot(x=list(epochs_list), y=hist['search_loss'], ax=ax1, label='Train Loss')\n"
"        if hist['val_loss']:\n"
"            sns.lineplot(x=list(epochs_list), y=hist['val_loss'], ax=ax1, label='Val Loss')\n"
"        ax1.set_xlabel('Epoch'); ax1.set_ylabel('Loss')\n"
"        ax1.set_title('Phase 1: Search Loss')\n"
"        ax1.axvline(hist['best_epoch'], color='red', linestyle='--', alpha=0.5,\n"
"                    label=f'Best ({hist[\"best_epoch\"]})')\n"
"        ax1.legend()\n"
"\n"
"        ax2.text(0.5, 0.5,\n"
"                 f'Best val loss: {hist[\"best_val_loss\"]:.4f}\\n'\n"
"                 f'Best epoch: {hist[\"best_epoch\"]}\\n'\n"
"                 f'Total time: {hist[\"total_time\"]:.1f}s',\n"
"                 transform=ax2.transAxes, ha='center', va='center', fontsize=14)\n"
"        ax2.set_title('Search Summary'); ax2.axis('off')\n"
"        fig.suptitle(f'{dataset_name} / {enc_type} -- Architecture Search',\n"
"                     fontsize=14, fontweight='bold')\n"
"        plt.tight_layout(); plt.show()"
)

md("## 5. Phase 2: Fine-tune on Extracted Subgraphs")

md("### 5a. Build / load subgraph caches (one-time cost, saved to disk)")

code(
"def _create_encoder(enc_type, in_ch, hid, n_layers, dropout):\n"
"    if enc_type == 'GCN': return GCN(in_ch, hid, hid, n_layers, dropout)\n"
"    elif enc_type == 'SAGE': return SAGE(in_ch, hid, hid, n_layers, dropout)\n"
"    elif enc_type == 'GAT': return GAT(in_ch, hid, hid, n_layers, dropout, heads=4)\n"
"    raise ValueError(enc_type)\n"
"\n"
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    data = r['data']; split_edge = r['split_edge']; msp = r['multi_scale_ppr']\n"
"\n"
"    for enc_type in ENCODERS:\n"
"        exp = r['experiments'][enc_type]\n"
"        exp['ft_encoder'] = _create_encoder(enc_type, FEATURE_DIM, HIDDEN_CHANNELS, NUM_LAYERS, DROPOUT)\n"
"        exp['ft_predictor'] = LinkPredictor(HIDDEN_CHANNELS, HIDDEN_CHANNELS, 1, NUM_LAYERS, DROPOUT)\n"
"        exp['ckpt_dir'] = f'checkpoints/learnable-ppr/{dataset_name}/{enc_type}'\n"
"        exp['cache_dir'] = f'cache/learnable-ppr/{dataset_name}/{enc_type}'\n"
"\n"
"        print(f'\\n[Cache] {dataset_name} / {enc_type} (top_k={TOP_K})')\n"
"        extractor = LearnablePPRExtractor(data, msp, exp['train_configs'], alpha=ALPHA, top_k=TOP_K)\n"
"        build_or_load_cache(extractor, split_edge, 'train', exp['cache_dir'])\n"
"\n"
"print('Caches ready.')"
)

md("### 5b. Fine-tune (resumes from checkpoint if interrupted)")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    data = r['data']; split_edge = r['split_edge']; msp = r['multi_scale_ppr']\n"
"\n"
"    for enc_type in ENCODERS:\n"
"        print(f'\\nPhase 2: {dataset_name} / {enc_type} (top_k={TOP_K})')\n"
"        exp = r['experiments'][enc_type]\n"
"\n"
"        ft_history = finetune_on_subgraphs(\n"
"            exp['ft_encoder'], exp['ft_predictor'], data, split_edge,\n"
"            msp, exp['train_configs'],\n"
"            alpha=ALPHA, top_k=TOP_K,\n"
"            epochs=FINETUNE_EPOCHS, batch_size=FINETUNE_BATCH_SIZE,\n"
"            lr=FINETUNE_LR, eval_steps=5, device=DEVICE,\n"
"            verbose=True, patience=FINETUNE_PATIENCE,\n"
"            max_subgraphs_per_forward=MAX_SUBGRAPHS_PER_FORWARD,\n"
"            checkpoint_dir=exp['ckpt_dir'],\n"
"            cache_dir=exp['cache_dir'],\n"
"            edges_per_epoch=EDGES_PER_EPOCH)\n"
"\n"
"        exp['ft_history'] = ft_history\n"
"        print(f'Best MRR: {ft_history[\"best_val_mrr\"]:.4f} at epoch {ft_history[\"best_epoch\"]}')"
)

md("## 6. Test Evaluation")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    data = r['data']; split_edge = r['split_edge']; msp = r['multi_scale_ppr']\n"
"\n"
"    for enc_type in ENCODERS:\n"
"        exp = r['experiments'][enc_type]\n"
"        cache_dir = f'cache/learnable-ppr/{dataset_name}/{enc_type}'\n"
"        test_results = evaluate_learnable_ppr(\n"
"            exp['ft_encoder'], exp['ft_predictor'],\n"
"            data, split_edge, msp, exp['test_configs'],\n"
"            split='test', alpha=ALPHA, top_k=TOP_K, device=DEVICE,\n"
"            cache_dir=cache_dir)\n"
"        exp['test_results'] = test_results\n"
"        print(f'\\n{dataset_name} / {enc_type}')\n"
"        print_evaluation_results(test_results, 'test')"
)

md("## 7. Fine-Tuning Training Curves")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    for enc_type in ENCODERS:\n"
"        exp = r['experiments'][enc_type]\n"
"        hist = exp.get('ft_history', {})\n"
"        if not hist: continue\n"
"\n"
"        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n"
"        epochs_list = range(1, len(hist['train_loss']) + 1)\n"
"        sns.lineplot(x=list(epochs_list), y=hist['train_loss'], ax=ax1, label='Train Loss')\n"
"        ax1.set_xlabel('Epoch'); ax1.set_ylabel('Loss'); ax1.set_title('Phase 2: Fine-tune Loss')\n"
"\n"
"        if hist['val_results']:\n"
"            val_mrrs = [vr['mrr'] for vr in hist['val_results']]\n"
"            eval_epochs = list(range(5, 5 * len(val_mrrs) + 1, 5))\n"
"            sns.lineplot(x=eval_epochs, y=val_mrrs, ax=ax2, marker='o')\n"
"            ax2.axhline(hist['best_val_mrr'], color='red', linestyle='--', alpha=0.5,\n"
"                        label=f'Best: {hist[\"best_val_mrr\"]:.4f}')\n"
"        ax2.set_xlabel('Epoch'); ax2.set_ylabel('MRR'); ax2.set_title('Validation MRR')\n"
"        ax2.legend()\n"
"\n"
"        fig.suptitle(f'{dataset_name} / {enc_type} -- Fine-tuning', fontsize=14, fontweight='bold')\n"
"        plt.tight_layout(); plt.show()"
)

md("## 8. Comparison with Static PPR Baselines")

code(
"def load_baseline_results():\n"
"    baselines = []\n"
"    base_dir = 'results/benchmark-ppr'\n"
"    if not os.path.exists(base_dir): return baselines\n"
"    for ds in os.listdir(base_dir):\n"
"        ds_dir = os.path.join(base_dir, ds)\n"
"        if not os.path.isdir(ds_dir): continue\n"
"        for exp_name in os.listdir(ds_dir):\n"
"            rp = os.path.join(ds_dir, exp_name, 'full_results.json')\n"
"            if os.path.exists(rp):\n"
"                with open(rp) as f:\n"
"                    baselines.append(json.load(f))\n"
"    return baselines\n"
"\n"
"baselines = load_baseline_results()\n"
"\n"
"rows = []\n"
"for b in baselines:\n"
"    if b['dataset'] in DATASETS and b['encoder'] in ENCODERS:\n"
"        rows.append({'Dataset': b['dataset'], 'Encoder': b['encoder'],\n"
"                     'Method': f'Static PPR (k={b[\"top_k\"]})',\n"
"                     'MRR': b['test_results']['mrr'],\n"
"                     'AUC': b['test_results']['auc']})\n"
"\n"
"for ds in DATASETS:\n"
"    r = all_results.get(ds, {})\n"
"    for enc in ENCODERS:\n"
"        exp = r.get('experiments', {}).get(enc, {})\n"
"        tr = exp.get('test_results')\n"
"        if tr:\n"
"            rows.append({'Dataset': ds, 'Encoder': enc, 'Method': 'Learnable PPR',\n"
"                         'MRR': tr['mrr'], 'AUC': tr['auc']})\n"
"\n"
"if rows:\n"
"    df = pd.DataFrame(rows)\n"
"    for metric in ['MRR', 'AUC']:\n"
"        fig, ax = plt.subplots(figsize=(max(8, 2 * len(rows)), 5))\n"
"        sns.barplot(data=df, x='Encoder', y=metric, hue='Method', ax=ax)\n"
"        ax.set_title(f'Test {metric} Comparison')\n"
"        ax.legend(loc='lower right')\n"
"        plt.tight_layout(); plt.show()\n"
"    display(df.pivot_table(index=['Dataset', 'Encoder'], columns='Method', values=['MRR', 'AUC']))\n"
"else:\n"
"    print('No baseline results found. Run the static PPR benchmark first.')"
)

md("## 9. Per-Edge Config Analysis by Node Degree")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    data = r['data']; msp = r['multi_scale_ppr']\n"
"\n"
"    degrees = torch.zeros(data.num_nodes, dtype=torch.long)\n"
"    for i in range(data.edge_index.size(1)):\n"
"        degrees[data.edge_index[0, i]] += 1\n"
"\n"
"    for enc_type in ENCODERS:\n"
"        exp = r['experiments'][enc_type]\n"
"        train_src = r['split_edge']['train']['source_node']\n"
"        configs = exp['train_configs']\n"
"\n"
"        src_degrees = degrees[train_src].numpy()\n"
"        config_labels = [f'({tu},{tv})' for tu, tv in msp.config_labels]\n"
"        config_names = np.array([config_labels[c.item()] for c in configs])\n"
"\n"
"        degree_bins = np.digitize(src_degrees, bins=[0, 5, 20, 50, 200, 1000])\n"
"        bin_labels = ['1-5', '6-20', '21-50', '51-200', '200+']\n"
"\n"
"        df_deg = pd.DataFrame({\n"
"            'Degree Bin': [bin_labels[min(b-1, len(bin_labels)-1)] for b in degree_bins],\n"
"            'Config': config_names,\n"
"        })\n"
"\n"
"        fig, ax = plt.subplots(figsize=(12, 5))\n"
"        sns.countplot(data=df_deg, x='Degree Bin', hue='Config', order=bin_labels, ax=ax)\n"
"        ax.set_title(f'{dataset_name} / {enc_type} -- Config by Source Node Degree')\n"
"        ax.set_ylabel('Count')\n"
"        ax.legend(title='(teleport_u, teleport_v)', bbox_to_anchor=(1.05, 1), loc='upper left')\n"
"        plt.tight_layout(); plt.show()"
)

md("## 10. t-SNE of Node Embeddings Colored by Config Preference")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    data = r['data']; msp = r['multi_scale_ppr']\n"
"\n"
"    for enc_type in ENCODERS:\n"
"        exp = r['experiments'][enc_type]\n"
"        model = exp['model']; model.eval()\n"
"\n"
"        with torch.no_grad():\n"
"            data_dev = data.to(DEVICE)\n"
"            H = model(data_dev.x, data_dev.edge_index).cpu().numpy()\n"
"\n"
"        train_src = r['split_edge']['train']['source_node']\n"
"        configs = exp['train_configs']\n"
"        node_config_votes = torch.zeros(data.num_nodes, msp.num_configs)\n"
"        for s, c in zip(train_src, configs):\n"
"            node_config_votes[s, c] += 1\n"
"\n"
"        dominant_config = node_config_votes.argmax(dim=1).numpy()\n"
"        has_votes = node_config_votes.sum(dim=1) > 0\n"
"\n"
"        mask = has_votes.numpy()\n"
"        indices = np.where(mask)[0]\n"
"        if len(indices) > 3000:\n"
"            indices = np.random.choice(indices, 3000, replace=False)\n"
"\n"
"        H_sub = H[indices]\n"
"        labels_sub = dominant_config[indices]\n"
"\n"
"        print(f't-SNE for {dataset_name}/{enc_type} ({len(indices)} nodes)...')\n"
"        tsne = TSNE(n_components=2, random_state=42, perplexity=30)\n"
"        emb_2d = tsne.fit_transform(H_sub)\n"
"\n"
"        config_labels = [f'({tu},{tv})' for tu, tv in msp.config_labels]\n"
"        fig, ax = plt.subplots(figsize=(10, 8))\n"
"        scatter = ax.scatter(emb_2d[:, 0], emb_2d[:, 1], c=labels_sub,\n"
"                             cmap='tab10', s=10, alpha=0.6)\n"
"        cbar = plt.colorbar(scatter, ax=ax, ticks=range(msp.num_configs))\n"
"        cbar.ax.set_yticklabels(config_labels)\n"
"        ax.set_title(f'{dataset_name} / {enc_type} -- t-SNE by dominant PPR config')\n"
"        ax.axis('off')\n"
"        plt.tight_layout(); plt.show()"
)

md("## 11. Subgraph Size Comparison")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]\n"
"    data = r['data']; split_edge = r['split_edge']; msp = r['multi_scale_ppr']\n"
"\n"
"    for enc_type in ENCODERS:\n"
"        exp = r['experiments'][enc_type]\n"
"        extractor = LearnablePPRExtractor(\n"
"            data, msp, exp['train_configs'], alpha=ALPHA, top_k=TOP_K)\n"
"\n"
"        src = split_edge['train']['source_node']\n"
"        dst = split_edge['train']['target_node']\n"
"        n_sample = min(500, src.size(0))\n"
"        sample_idx = torch.randperm(src.size(0))[:n_sample]\n"
"\n"
"        sizes_learned = []; configs_used = []\n"
"        for i in sample_idx:\n"
"            u, v = src[i].item(), dst[i].item()\n"
"            _, sel, meta = extractor.extract_subgraph(u, v, i.item())\n"
"            sizes_learned.append(meta['num_nodes_selected'])\n"
"            configs_used.append(meta['config_idx'])\n"
"\n"
"        config_labels = [f'({tu},{tv})' for tu, tv in msp.config_labels]\n"
"        df_sz = pd.DataFrame({\n"
"            'Subgraph Size': sizes_learned,\n"
"            'Config': [config_labels[c] for c in configs_used],\n"
"        })\n"
"\n"
"        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n"
"        sns.histplot(sizes_learned, bins=30, ax=ax1, kde=True)\n"
"        ax1.axvline(np.mean(sizes_learned), color='red', linestyle='--',\n"
"                    label=f'Mean: {np.mean(sizes_learned):.0f}')\n"
"        ax1.set_xlabel('Subgraph Size (nodes)'); ax1.set_title('Size Distribution'); ax1.legend()\n"
"\n"
"        sns.boxplot(data=df_sz, x='Config', y='Subgraph Size', ax=ax2)\n"
"        ax2.set_title('Size by Config'); ax2.tick_params(axis='x', rotation=45)\n"
"\n"
"        fig.suptitle(f'{dataset_name} / {enc_type} -- Subgraph Sizes (top_k={TOP_K})',\n"
"                     fontsize=14, fontweight='bold')\n"
"        plt.tight_layout(); plt.show()"
)

md("## 12. Save Results")

code(
"for dataset_name in DATASETS:\n"
"    r = all_results[dataset_name]; msp = r['multi_scale_ppr']\n"
"    for enc_type in ENCODERS:\n"
"        exp = r['experiments'][enc_type]\n"
"        tr = exp.get('test_results')\n"
"        if not tr: continue\n"
"\n"
"        save_dir = f'results/benchmark-learnable-ppr/{dataset_name}/{enc_type}'\n"
"        os.makedirs(save_dir, exist_ok=True)\n"
"\n"
"        result_json = {\n"
"            'dataset': dataset_name, 'encoder': enc_type,\n"
"            'teleport_values': TELEPORT_VALUES, 'alpha': ALPHA, 'top_k': TOP_K,\n"
"            'test_results': {k: float(v) for k, v in tr.items()},\n"
"            'config_distribution': {\n"
"                'train': exp['train_counts'].tolist(),\n"
"                'test': exp['test_counts'].tolist(),\n"
"                'labels': [f'({tu},{tv})' for tu, tv in msp.config_labels],\n"
"            },\n"
"            'search_time': exp['search_history']['total_time'],\n"
"            'finetune_best_mrr': exp['ft_history']['best_val_mrr'],\n"
"            'finetune_best_epoch': exp['ft_history']['best_epoch'],\n"
"        }\n"
"        with open(os.path.join(save_dir, 'full_results.json'), 'w') as f:\n"
"            json.dump(result_json, f, indent=2)\n"
"        print(f'Saved: {save_dir}/full_results.json')\n"
"\n"
"        run_id = time.strftime('%Y%m%d_%H%M%S')\n"
"        run_dir = os.path.join(save_dir, 'runs', run_id)\n"
"        alpha_save = ALPHA if isinstance(ALPHA, list) else [float(ALPHA)]\n"
"        extra_hp = {\n"
"            'feature_dim': FEATURE_DIM,\n"
"            'hidden_channels': HIDDEN_CHANNELS,\n"
"            'num_layers': NUM_LAYERS,\n"
"            'dropout': DROPOUT,\n"
"            'search_epochs': SEARCH_EPOCHS,\n"
"            'search_batch_size': SEARCH_BATCH_SIZE,\n"
"            'search_lr': SEARCH_LR,\n"
"            'search_patience': SEARCH_PATIENCE,\n"
"            'temperature': TEMPERATURE,\n"
"            'finetune_epochs': FINETUNE_EPOCHS,\n"
"            'finetune_batch_size': FINETUNE_BATCH_SIZE,\n"
"            'finetune_lr': FINETUNE_LR,\n"
"            'finetune_patience': FINETUNE_PATIENCE,\n"
"            'device': DEVICE,\n"
"        }\n"
"        save_learnable_ppr_experiment(\n"
"            run_dir, dataset_name, enc_type, run_id,\n"
"            TELEPORT_VALUES, alpha_save, TOP_K,\n"
"            exp, msp, extra_config=extra_hp)\n"
"        print(f'Saved run artifacts: {run_dir}')\n"
"print('Done!')"
)

with open(r"d:\Work + Project\Thesis\MTCH\learnable_ppr.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Notebook written successfully")
